/* ============================================================
 * Centralized Supabase configuration for ToolManagement.
 * Single source of truth — do not hard-code Supabase URL / anon key
 * anywhere else in the project. Each HTML file reads its own entry.
 * Generated by refactor; values match the project's original backends.
 * ============================================================ */
(function (root) {
  var CONFIG = {
  "index.html": {
    "url": "https://hlnxepbsmlzmvtaruklv.supabase.co",
    "key": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsbnhlcGJzbWx6bXZ0YXJ1a2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcyMzM4NzUsImV4cCI6MjEwMjgwOTg3NX0.ERd1WBzu2xLC3RHqW1D46ZUb3AENyP35KUs9cfBFAHM"
  }
};

  function currentFileName() {
    try {
      var p = (root.location && root.location.pathname) || '';
      var n = p.split('/').pop() || '';
      return n || 'index.html';
    } catch (e) { return 'index.html'; }
  }

  root.SUPABASE_CONFIG = CONFIG;
  root.getSupabaseConfig = function (name) {
    return CONFIG[name || currentFileName()] || null;
  };
})(typeof window !== 'undefined' ? window : globalThis);
