/* ============================================================
 * Centralized Supabase configuration for ToolManagement.
 * Single source of truth — do not hard-code Supabase URL / anon key
 * anywhere else in the project. Each HTML file reads its own entry.
 * Generated by refactor; values match the project's original backends.
 * ============================================================ */
(function (root) {
  var CONFIG = {
  "index.html": {
    "url": "https://rnsjiqbbeywgbnqsojce.supabase.co",
    "key": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuc2ppcWJiZXl3Z2JucXNvamNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0OTExNjAsImV4cCI6MjA5MzA2NzE2MH0.1BrlS__GNAMFbBmudl6gUJwJ9j_zoDdAj9rtfhBkhdk" }
};

  function currentFileName() {
    try {
      var p = (root.location && root.location.pathname) || '';
      var n = p.split('/').pop() || '';
      return n || 'index.html';
    } catch (e) { return 'index.html'; }
  }

  root.SUPABASE_CONFIG = CONFIG;
  root.getSupabaseConfig = function (name) {
    return CONFIG[name || currentFileName()] || null;
  };
})(typeof window !== 'undefined' ? window : globalThis);
